export default {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    NEW_TWEET: 'NEW_TWEET',
    NEW_TWEET_LIST: 'NEW_TWEET_LIST',

    //SETTINGS ACTIONS
    SWITCH_VIEW: 'SWITCH_VIEW',
    LISTEN_TO_NEW_USER: 'LISTEN_TO_NEW_USER',

    //SOCKET ACTIONS
    UPDATE_SOCKET_STATUS: 'UPDATE_SOCKET_STATUS'
}
