export default {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    NEW_TWEET: 'NEW_TWEET',
    NEW_TWEET_LIST: 'NEW_TWEET_LIST',

    //SETTINGS ACTIONS
    SWITCH_VIEW: 'SWITCH_VIEW',
    LISTEN_TO_NEW_USER: 'LISTEN_TO_NEW_USER',

    //SOCKET ACTIONS
    ADD_CLIENT_SOCKET: 'ADD_CLIENT_SOCKET',
    UPDATE_SOCKET_STATUS: 'UPDATE_SOCKET_STATUS',
    LISTEN_TO_NEW_USERS: 'LISTEN_TO_NEW_USERS',
    LISTEN_WAS_SUCCESSFUL: 'LISTEN_WAS_SUCCESSFUL',

    //ERROR ACTIONS
    THROW_ERROR: 'THROW_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR'
}
